name: Dependabot auto-merge

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled, ready_for_review]

permissions:
  contents: write
  pull-requests: write
  checks: read
  statuses: read

jobs:
  automerge:
    if: |
      github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto-merge minor and patch updates
        if: contains(steps.metadata.outputs.update-type, 'semver:minor') || contains(steps.metadata.outputs.update-type, 'semver:patch')
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_DELETE_BRANCH: "true"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
      - name: Comment on major updates
        if: contains(steps.metadata.outputs.update-type, 'semver:major')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "This is a major release update. Auto-merge is disabled. A maintainer review and manual merge is required."
            })
