name: Lint (ktlint)

on:
  pull_request:
    branches: [ "main", "dev" ]
  push:
    branches: [ "main", "dev" ]

jobs:
  ktlint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
      - name: Download ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.2.1/ktlint_1.2.1_linux_x64.zip
          unzip -q ktlint_1.2.1_linux_x64.zip -d ktlintbin
          echo "${GITHUB_WORKSPACE}/ktlintbin" >> $GITHUB_PATH
      - name: Run ktlint
        run: |
          ktlint --version || true
          ktlint "**/*.kt" || true
