name: Lint (ktlint)

on:
  pull_request:
    branches: [ "main", "dev" ]
  push:
    branches: [ "main", "dev" ]

jobs:
  ktlint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
      - name: Download ktlint
        run: |
          KTLINT_VERSION=1.7.1
          curl -sSfL -o ktlint.zip https://github.com/pinterest/ktlint/releases/download/${KTLINT_VERSION}/ktlint-${KTLINT_VERSION}.zip
          unzip -q ktlint.zip -d ktlintbin
          chmod +x ktlintbin/ktlint-1.7.1/bin/ktlint
          echo "${GITHUB_WORKSPACE}/ktlintbin" >> $GITHUB_PATH
      - name: Run ktlint
        run: |
          ktlint --version 
          ktlint "**/*.kt" 
